### ISSUE TITLE
Broken image in lectures/flow/switch

### ISSUE THREAD

**Issue by jweeks2023** [princomp/princomp.github.io#23]
https://github.com/princomp/princomp.github.io/blob/0d923a06743e326758087d757aa12bcd0898987f/source/lectures/flow/switch.md?plain=1#L13

**Comment by aubertc** [comment]
https://github.com/princomp/princomp.github.io/commit/ddd2cd04c4b8b16ed777cfc5436c267a2f7c7451 will solve that.

**Comment by jweeks2023** [comment]
It is fixed, however, it seems this image is not accessible for dark mode users. See picture below:

![image](https://github.com/princomp/princomp.github.io/assets/88799372/23c5d43c-e225-41e0-ac38-4d1f9c38832c)

**Comment by jweeks2023** [comment]
This is actually a widespread issue with these diagrams, which I believe are related to the fact that you are using SVGs for these. There are multiple ways to approach this (i.e., add backgrounds to them, modify the color scheme to have light and dark variants, etc.), but each solution has its pros and cons, so I will leave that to you to decide how to proceed.

**Comment by aubertc** [comment]
Ok, I'll try to think of a global solution.

**Comment by aubertc** [comment]
The background of UML class diagrams is not transparent anymore:

![Screenshot_20241213_105357](https://github.com/user-attachments/assets/0fa4f481-e3ad-4f4f-bb21-b82966232a1e)

The issue remains for some other images: cf. https://github.com/princomp/princomp.github.io/issues/49
